### PR TITLE
Ubuntu support

### PR DESCRIPTION
**Pull request by benbc**
Don't know if you're interested in modifying this to support Linux, but if you are, here's a working version (tested on Ubuntu 10.04).

It introduces a switch on OS in a couple of places. I put some supporting code for this into `config.sh` because that seemed the sensible place for it. I don't have access to either a Mac or some other non-Linux machine, so I'm afraid the Mac case and the error case are untested.

I had to change two things.
1.  remove use of `hdiutil` for mounting the ISO
   -  I guess that it might be possible to use `mount` on OSX as well, in order to
     remove the conditional logic
2.  modify permissions on the private SSH key
   -  I wasn't sure where the best place to do this is; I put it in `config.sh` because
     that seems the only place that ensures it will get called before the first SSH
     operation (without restructuring the Makefile to introduce dependencies, or
     something); you may want to move it to somewhere more sensible
   -  again, you may want to get rid of the conditional logic here and do the `chmod`
     on the Mac as well

Hope this is useful to you.

-Ben

### CODE REVIEW

**Comment by benbc** [comment]
I've just run into another issue which needs fixing with this. You use an environment variable called USERNAME to define the user on the VM. That variable is already defined on Ubuntu to the name of the logged in user. So the user getting created isn't 'vagrant' by default.

There is a workaround, adding `config.ssh.username` to the Vagrantfile.

When I get a minute I'll produce a patch to change the variable name.

-Ben

**Comment by rcrowley** [comment]
@benbc does this version of the patch work well for you?  (Nevermind the `USERNAME` issue just yet.)

**Comment by benbc** [comment]
Yup, tested that and it works fine. (If you don't mind a couple of `./build-iso: 21: hdiutil: not found`s.)

**Comment by rcrowley** [comment]
Closed by d9e05c1f88b8629a9590f70ebf7a968f0f309740 being merged to master.  Thanks @benbc for the help and testing!

**Pull request closed without merging**
